// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb261WKKB_-UwJnygp76_k9kWmXxzu8_Q',
    appId: '1:892601144354:web:bcd9b4514789e33431267b',
    messagingSenderId: '892601144354',
    projectId: 'rentride-8b74b',
    authDomain: 'rentride-8b74b.firebaseapp.com',
    storageBucket: 'rentride-8b74b.appspot.com',
    measurementId: 'G-EEJXV0FMHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVyI1fAV5VwsyUyGTfr23l5XZ4gFHnsN0',
    appId: '1:892601144354:android:7a7f795e60491cc831267b',
    messagingSenderId: '892601144354',
    projectId: 'rentride-8b74b',
    storageBucket: 'rentride-8b74b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACOnvTv8NvRhCp2rOufzKrIYSOFLcBpd4',
    appId: '1:892601144354:ios:c249a450c50cc5a331267b',
    messagingSenderId: '892601144354',
    projectId: 'rentride-8b74b',
    storageBucket: 'rentride-8b74b.appspot.com',
    iosBundleId: 'com.example.rentedbike',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACOnvTv8NvRhCp2rOufzKrIYSOFLcBpd4',
    appId: '1:892601144354:ios:cdc05e9f08a8f79d31267b',
    messagingSenderId: '892601144354',
    projectId: 'rentride-8b74b',
    storageBucket: 'rentride-8b74b.appspot.com',
    iosBundleId: 'com.example.rentedbike.RunnerTests',
  );
}
